# flight_routes/docker-compose.yml
services:
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/code
      - ./media:/code/media
    environment:
      - PYTHONUNBUFFERED=1
